# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title
relative_permalinks: false

# Setup
title:            Kelly Ripple
tagline:          'TAGLINE'
description:      'Software Engineer'
url:              http://kellyripple.com
baseurl:          /

author:
  name:           'Kelly Ripple'
  url:            https://twitter.com/krippleffect

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kripple/hyde

excerpt_separator: <!--break-->